// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "UrlShortenStorageService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::social_network;

class UrlShortenStorageServiceHandler : virtual public UrlShortenStorageServiceIf {
 public:
  UrlShortenStorageServiceHandler() {
    // Your initialization goes here
  }

  void StoreUrls(const std::vector<Url> & target_urls) {
    // Your implementation goes here
    printf("StoreUrls\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<UrlShortenStorageServiceHandler> handler(new UrlShortenStorageServiceHandler());
  ::std::shared_ptr<TProcessor> processor(new UrlShortenStorageServiceProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

