// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "UserTimelineStorageService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::social_network;

class UserTimelineStorageServiceHandler : virtual public UserTimelineStorageServiceIf {
 public:
  UserTimelineStorageServiceHandler() {
    // Your initialization goes here
  }

  void UpdateUserTimeline(const int64_t user_id, const int64_t post_id, const int64_t timestamp) {
    // Your implementation goes here
    printf("UpdateUserTimeline\n");
  }

  void GetUserTimeline(std::vector<int64_t> & _return, const int64_t user_id, const int32_t start, const int32_t stop) {
    // Your implementation goes here
    printf("GetUserTimeline\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<UserTimelineStorageServiceHandler> handler(new UserTimelineStorageServiceHandler());
  ::std::shared_ptr<TProcessor> processor(new UserTimelineStorageServiceProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

